config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

RedmineApp::Application.routes.draw do
  get 'download_history/:attachment_id' => 'download_history#show', as: :attachment_history
end

app/models/download_history.rb
class DownloadHistory < ActiveRecord::Base
  belongs_to :attachment
  belongs_to :user

  def self.to_csv
    attributes = %w(Login Date)

    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |user|
        csv << attributes.map { |attr| user.send(attr) }
      end
    end
  end
end

app/controllers/download_history_controller.rb
class DownloadHistoryController < ApplicationController
  before_action :check_ability

  def show
    @attachment = Attachment.find(params[:attachment_id])
    @histories = DownloadHistory.where(attachment_id: @attachment.id)

    respond_to do |format|
      format.pdf { send_file_headers! type: 'application/pdf', filename: 'issues.pdf' }
      format.html
    end
  end

  private

  def check_ability
    render_404 unless User.current.allowed_to?(:view_attachment_history, nil, global: true)
  end

end

app/helpers/download_history_helper.rb
module DownloadHistoryHelper

  def history_page_to_pdf(histories, attachment)
    pdf = Redmine::Export::PDF::ITCPDF.new(current_language)
    pdf.set_title("Download History - #{attachment.filename}")
    pdf.alias_nb_pages
    pdf.footer_date = format_date(Date.today)
    pdf.add_page
    pdf.SetFontStyle('B', 11)
    pdf.RDMMultiCell(190, 5, "Download History - #{attachment.filename}")
    pdf.ln

    page_width    = pdf.get_page_width  # 297
    left_margin   = pdf.get_original_margins['left'] # 10
    right_margin  = pdf.get_original_margins['right'] # 10
    row_height    = 4
    table_width   = page_width - right_margin - left_margin

    pdf.RDMMultiCell(table_width, 5, "##{attachment.container.try(:id)}: #{attachment.container.try(:subject)}")
    pdf.ln

    pdf.SetFontStyle('B', 8)
    pdf.set_fill_color(230, 230, 230)
    pdf.RDMMultiCell(table_width / 2, row_height, 'Login', 1, '', 1, 0)
    pdf.RDMMultiCell(table_width / 2, row_height, 'Date', 1, '', 1, 0)
    pdf.ln

    pdf.SetFontStyle('', 8)
    pdf.set_fill_color(255, 255, 255)
    histories.each do |history|
      pdf.RDMMultiCell(table_width / 2, row_height, history.user.login, 1, '', 1, 0)
      pdf.RDMMultiCell(table_width / 2, row_height, format_time(history.created_at), 1, '', 1, 0)
      pdf.ln
    end

    pdf.output
  end

end

app/views/attachments/_links.html.erb
<div class="attachments">
<div class="contextual">
  <%= link_to image_tag('edit.png'),
        container_attachments_edit_path(container),
        :title => l(:label_edit_attachments) if options[:editable] %>
</div>
<% for attachment in attachments %>
<p><%= link_to_attachment attachment, :class => 'icon icon-attachment', :download => true -%>
  <% if attachment.is_text? %>
    <%= link_to image_tag('magnifier.png'),
                :controller => 'attachments', :action => 'show',
                :id => attachment, :filename => attachment.filename %>
  <% end %>
  <%= h(" - #{attachment.description}") unless attachment.description.blank? %>
  <span class="size">(<%= number_to_human_size attachment.filesize %>)</span>
  <% if options[:deletable] %>
    <%= link_to image_tag('delete.png'), attachment_path(attachment),
                                         :data => {:confirm => l(:text_are_you_sure)},
                                         :method => :delete,
                                         :class => 'delete',
                                         :title => l(:button_delete) %>
  <% end %>
  <% if options[:author] %>
    <span class="author">
      <%= h(attachment.author) %>, <%= format_time(attachment.created_on)%>
      <% if User.current.allowed_to?(:view_attachment_history, nil, global: true) %>
        <%= link_to 'History', attachment_history_path(attachment), class: 'icon icon-history' %>
      <% end %>
    </span>
  <% end %>
  </p>
<% end %>
<% if defined?(thumbnails) && thumbnails %>
  <% images = attachments.select(&:thumbnailable?) %>
  <% if images.any? %>
  <div class="thumbnails">
    <% images.each do |attachment| %>
      <div><%= thumbnail_tag(attachment) %></div>
    <% end %>
  </div>
  <% end %>
<% end %>
</div>

app/views/download_history/show.html.erb
<span>
  <%= link_to '<<- Back', send("#{@attachment.container.class.name.underscore}_path", @attachment.container) %>
</span>

<h2>Download History</h2>

<table class="list wiki-page-versions">
  <thead>
    <tr>
      <th>Login</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <% @histories.each do |history| %>
      <tr class="wiki-page-version">
        <td class="author">
          <%= history.user.login %>
        </td>
        <td>
          <%= format_time(history.created_at) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% other_formats_links do |f| %>
  <%= f.link_to 'PDF', url: { id: @attachment.id } %>
<% end %>

app/views/download_history/show.pdf.erb
<%= raw history_page_to_pdf(@histories, @attachment) %>